# Generated by Django 3.2.5 on 2022-05-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='productcategory',
            index_together={('id', 'slug')},
        ),
    ]
